name: Upload Release Asset

on:
  release:
    types: [published]

jobs:
  upload:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Permet au script d'ajouter des fichiers aux releases
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # --- LA CORRECTION EST ICI : setup-node ---
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build Javascript Bundle
        run: npm run build

      - name: Upload JS Bundle to Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/thermostat-simple-card.js
          asset_name: thermostat-simple-card.js
          tag: ${{ github.ref }}
          overwrite: true
